const actions = {
    HOME: {
        'GETHOME': 'GETHOME',
        'LOADHOME': 'LOADHOME'
    },
    USER:{
        'CREATEUSER': 'CREATEUSER',
        'STOREUSER': 'STOREUSER',
        'CREATEUSERSUCCESS': 'CREATEUSERSUCCESS',
        'CREATEUSERFAILURE': 'CREATEUSERFAILURE',
        'AUTHENTICATEUSER': 'AUTHENTICATEUSER',
        'AUTHUSERSUCCESS': 'AUTHUSERSUCCESS',
        'AUTHUSERFAILURE': 'AUTHUSERFAILURE',
        'GETPROJECTLIST': 'GETPROJECTLIST',
        'GETPROJECTLISTSUCCESS': 'GETPROJECTLISTSUCCESS',
        'GETPROJECTLISTFAILURE': 'GETPROJECTLISTFAILURE'
    },
    ABOUT: {
        'GETABOUT': 'GETABOUT',
        'LOADABOUT': 'LOADABOUT'
    }
};
export default actions;